add check if build exists

diff --git a/.github/workflows/exercice2.yml b/.github/workflows/exercice2.yml
--- a/.github/workflows/exercice2.yml
+++ b/.github/workflows/exercice2.yml
@@ -28,6 +28,13 @@ jobs:
       - name: run build
         run: npm run build
 
+      - name: check if build exists
+        run: |
+          if [ ! -d dist]; then
+            echo "::error:: Le dossier dist/ n'existe pas"
+            exit 1
+          fi
+
       - name: Create artefact
         uses: actions/upload-artifact@v7
         with:
